param(
    [string]$Destination = "backend\\ffmpeg",
    [switch]$SkipRestart
)

$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot

Write-Host "[ffmpeg-installer] Destination: $Destination" -ForegroundColor Cyan

# Known good Windows static build (essentials). Change if needed.
$ffmpegUrl = 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip'

$tempZip = Join-Path $env:TEMP "ffmpeg_download.zip"
if (Test-Path $tempZip) { Remove-Item $tempZip -Force }

Write-Host "[ffmpeg-installer] Downloading FFmpeg..." -NoNewline
Invoke-WebRequest -Uri $ffmpegUrl -OutFile $tempZip -UseBasicParsing
Write-Host " done"

$destFull = Join-Path $PSScriptRoot $Destination
if (-not (Test-Path $destFull)) { New-Item -ItemType Directory -Path $destFull | Out-Null }

Write-Host "[ffmpeg-installer] Extracting to $destFull..."
Expand-Archive -Path $tempZip -DestinationPath $destFull -Force

# Locate bin directory that contains ffmpeg.exe
Write-Host "[ffmpeg-installer] Locating ffmpeg binary..."
$ffmpegExe = Get-ChildItem -Path $destFull -Recurse -Filter ffmpeg.exe -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $ffmpegExe) {
    Write-Error "ffmpeg.exe not found after extraction. Check the downloaded archive or extract location."
    exit 1
}

$ffmpegBin = $ffmpegExe.DirectoryName
Write-Host "[ffmpeg-installer] Found ffmpeg at: $ffmpegBin"

# Update .env files (project root and backend/)
function Set-EnvValue($envPath, $key, $value) {
    if (-not (Test-Path $envPath)) {
        Write-Host "[ffmpeg-installer] Creating $envPath"
        "# Auto-generated by install_ffmpeg.ps1`n$key=$value`n" | Out-File -FilePath $envPath -Encoding UTF8
        return
    }
    $content = Get-Content $envPath -Raw
    if ($content -match "(?m)^[#\s]*$key\s*=.*$") {
        $new = $content -replace "(?m)^[#\s]*($key)\s*=.*$", "`$1=$value"
        $new | Out-File -FilePath $envPath -Encoding UTF8
    } else {
        Add-Content -Path $envPath -Value "`n$key=$value"
    }
}

$projEnv = Join-Path $PSScriptRoot '.env'
$backendEnv = Join-Path $PSScriptRoot 'backend\.env'
$relBin = (Get-Item $ffmpegBin).FullName

Set-EnvValue -envPath $projEnv -key 'FFMPEG_LOCATION' -value $relBin
Set-EnvValue -envPath $backendEnv -key 'FFMPEG_LOCATION' -value $relBin

# Cleanup
Remove-Item $tempZip -Force -ErrorAction SilentlyContinue

Write-Host "[ffmpeg-installer] FFmpeg installed and .env updated." -ForegroundColor Green
Write-Host "FFMPEG_LOCATION=$relBin"

if (-not $SkipRestart) {
    Write-Host "\nPlease restart the server to apply the change. If you want me to restart it now, press Y and Enter." -ForegroundColor Yellow
    $resp = Read-Host "Restart server now? (Y/N)"
    if ($resp -match '^[Yy]') {
        Write-Host "Attempting to restart run_local.ps1..." -ForegroundColor Cyan
        # Try to start a new instance of the run_local script in a separate window
        Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", (Join-Path $PSScriptRoot 'run_local.ps1')
        Write-Host "Started new run_local.ps1 process. You may need to stop the old one manually." -ForegroundColor Green
    } else {
        Write-Host "Skipped restart. Please restart .\run_local.ps1 manually." -ForegroundColor Yellow
    }
}
